### ISSUE TITLE
Git push on this repository

### ISSUE THREAD

**Issue by ghost** [githubschool/scratch#100]
# Permission Denied
I followed up with this repo for the github official tutorials guide. At the point of pushing code unto this repository, i got a permission denied. Here's a snapshot of the problem.
![Screenshot from 2023-01-06 23-04-27](https://user-images.githubusercontent.com/82376387/211107964-ff51c07a-c6b1-418c-99a9-605afffcf15b.png)

**Comment by Pob1-Balin** [comment]
Can i get any help ?
